default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: up_app
  password: up_app
  host: localhost

development:
  <<: *default
  database: up_app_development

test:
  <<: *default
  database: up_app_test

production:
  <<: *default
  database: up_app_production
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
